#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KütüphaneTakipProgramı
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	//[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Kütüphane")]
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KutuphaneOtomasyon")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEMANETDURUM(EMANETDURUM instance);
    partial void UpdateEMANETDURUM(EMANETDURUM instance);
    partial void DeleteEMANETDURUM(EMANETDURUM instance);
    partial void InsertKİTAP(KİTAP instance);
    partial void UpdateKİTAP(KİTAP instance);
    partial void DeleteKİTAP(KİTAP instance);
    partial void InsertKULLANICI(KULLANICI instance);
    partial void UpdateKULLANICI(KULLANICI instance);
    partial void DeleteKULLANICI(KULLANICI instance);
    partial void InsertÜYE(ÜYE instance);
    partial void UpdateÜYE(ÜYE instance);
    partial void DeleteÜYE(ÜYE instance);
    #endregion
		
		public DataClasses1DataContext() :
                base(global::KütüphaneTakipProgramı.Properties.Settings.Default.KütüphaneConnectionString, mappingSource)
        {
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<EMANETDURUM> EMANETDURUMs
		{
			get
			{
				return this.GetTable<EMANETDURUM>();
			}
		}
		
		public System.Data.Linq.Table<KİTAP> KİTAPs
		{
			get
			{
				return this.GetTable<KİTAP>();
			}
		}
		
		public System.Data.Linq.Table<KULLANICI> KULLANICIs
		{
			get
			{
				return this.GetTable<KULLANICI>();
			}
		}
		
		public System.Data.Linq.Table<ÜYE> ÜYEs
		{
			get
			{
				return this.GetTable<ÜYE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EMANETDURUM")]
	public partial class EMANETDURUM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Kayıtno;
		
		private int _ÜyeNo;
		
		private string _ÜyeAdı;
		
		private int _BarkodNo;
		
		private string _KitapAdı;
		
		private string _Durum;
		
		private System.Nullable<System.DateTime> _Alıştarihi;
		
		private System.Nullable<System.DateTime> _Veriştarihi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKayıtnoChanging(int value);
    partial void OnKayıtnoChanged();
    partial void OnÜyeNoChanging(int value);
    partial void OnÜyeNoChanged();
    partial void OnÜyeAdıChanging(string value);
    partial void OnÜyeAdıChanged();
    partial void OnBarkodNoChanging(int value);
    partial void OnBarkodNoChanged();
    partial void OnKitapAdıChanging(string value);
    partial void OnKitapAdıChanged();
    partial void OnDurumChanging(string value);
    partial void OnDurumChanged();
    partial void OnAlıştarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnAlıştarihiChanged();
    partial void OnVeriştarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnVeriştarihiChanged();
    #endregion
		
		public EMANETDURUM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kayıtno", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Kayıtno
		{
			get
			{
				return this._Kayıtno;
			}
			set
			{
				if ((this._Kayıtno != value))
				{
					this.OnKayıtnoChanging(value);
					this.SendPropertyChanging();
					this._Kayıtno = value;
					this.SendPropertyChanged("Kayıtno");
					this.OnKayıtnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ÜyeNo", DbType="Int NOT NULL")]
		public int ÜyeNo
		{
			get
			{
				return this._ÜyeNo;
			}
			set
			{
				if ((this._ÜyeNo != value))
				{
					this.OnÜyeNoChanging(value);
					this.SendPropertyChanging();
					this._ÜyeNo = value;
					this.SendPropertyChanged("ÜyeNo");
					this.OnÜyeNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ÜyeAdı", DbType="NChar(20)")]
		public string ÜyeAdı
		{
			get
			{
				return this._ÜyeAdı;
			}
			set
			{
				if ((this._ÜyeAdı != value))
				{
					this.OnÜyeAdıChanging(value);
					this.SendPropertyChanging();
					this._ÜyeAdı = value;
					this.SendPropertyChanged("ÜyeAdı");
					this.OnÜyeAdıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarkodNo", DbType="Int NOT NULL")]
		public int BarkodNo
		{
			get
			{
				return this._BarkodNo;
			}
			set
			{
				if ((this._BarkodNo != value))
				{
					this.OnBarkodNoChanging(value);
					this.SendPropertyChanging();
					this._BarkodNo = value;
					this.SendPropertyChanged("BarkodNo");
					this.OnBarkodNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KitapAdı", DbType="NChar(50)")]
		public string KitapAdı
		{
			get
			{
				return this._KitapAdı;
			}
			set
			{
				if ((this._KitapAdı != value))
				{
					this.OnKitapAdıChanging(value);
					this.SendPropertyChanging();
					this._KitapAdı = value;
					this.SendPropertyChanged("KitapAdı");
					this.OnKitapAdıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Durum", DbType="NChar(20)")]
		public string Durum
		{
			get
			{
				return this._Durum;
			}
			set
			{
				if ((this._Durum != value))
				{
					this.OnDurumChanging(value);
					this.SendPropertyChanging();
					this._Durum = value;
					this.SendPropertyChanged("Durum");
					this.OnDurumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alıştarihi", DbType="Date")]
		public System.Nullable<System.DateTime> Alıştarihi
		{
			get
			{
				return this._Alıştarihi;
			}
			set
			{
				if ((this._Alıştarihi != value))
				{
					this.OnAlıştarihiChanging(value);
					this.SendPropertyChanging();
					this._Alıştarihi = value;
					this.SendPropertyChanged("Alıştarihi");
					this.OnAlıştarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Veriştarihi", DbType="Date")]
		public System.Nullable<System.DateTime> Veriştarihi
		{
			get
			{
				return this._Veriştarihi;
			}
			set
			{
				if ((this._Veriştarihi != value))
				{
					this.OnVeriştarihiChanging(value);
					this.SendPropertyChanging();
					this._Veriştarihi = value;
					this.SendPropertyChanged("Veriştarihi");
					this.OnVeriştarihiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KİTAP")]
	public partial class KİTAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BarkodNo;
		
		private string _KitapAdı;
		
		private string _Yazarı;
		
		private string _YayınEvi;
		
		private System.Nullable<int> _SayfaSayısı;
		
		private System.Nullable<int> _StokSayısı;
		
		private System.Nullable<System.DateTime> _BasımYılı;
		
		private string _Durum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBarkodNoChanging(int value);
    partial void OnBarkodNoChanged();
    partial void OnKitapAdıChanging(string value);
    partial void OnKitapAdıChanged();
    partial void OnYazarıChanging(string value);
    partial void OnYazarıChanged();
    partial void OnYayınEviChanging(string value);
    partial void OnYayınEviChanged();
    partial void OnSayfaSayısıChanging(System.Nullable<int> value);
    partial void OnSayfaSayısıChanged();
    partial void OnStokSayısıChanging(System.Nullable<int> value);
    partial void OnStokSayısıChanged();
    partial void OnBasımYılıChanging(System.Nullable<System.DateTime> value);
    partial void OnBasımYılıChanged();
    partial void OnDurumChanging(string value);
    partial void OnDurumChanged();
    #endregion
		
		public KİTAP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarkodNo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int BarkodNo
		{
			get
			{
				return this._BarkodNo;
			}
			set
			{
				if ((this._BarkodNo != value))
				{
					this.OnBarkodNoChanging(value);
					this.SendPropertyChanging();
					this._BarkodNo = value;
					this.SendPropertyChanged("BarkodNo");
					this.OnBarkodNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KitapAdı", DbType="NChar(100) NOT NULL", CanBeNull=false)]
		public string KitapAdı
		{
			get
			{
				return this._KitapAdı;
			}
			set
			{
				if ((this._KitapAdı != value))
				{
					this.OnKitapAdıChanging(value);
					this.SendPropertyChanging();
					this._KitapAdı = value;
					this.SendPropertyChanged("KitapAdı");
					this.OnKitapAdıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yazarı", DbType="NChar(100)")]
		public string Yazarı
		{
			get
			{
				return this._Yazarı;
			}
			set
			{
				if ((this._Yazarı != value))
				{
					this.OnYazarıChanging(value);
					this.SendPropertyChanging();
					this._Yazarı = value;
					this.SendPropertyChanged("Yazarı");
					this.OnYazarıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YayınEvi", DbType="NChar(100)")]
		public string YayınEvi
		{
			get
			{
				return this._YayınEvi;
			}
			set
			{
				if ((this._YayınEvi != value))
				{
					this.OnYayınEviChanging(value);
					this.SendPropertyChanging();
					this._YayınEvi = value;
					this.SendPropertyChanged("YayınEvi");
					this.OnYayınEviChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SayfaSayısı", DbType="Int")]
		public System.Nullable<int> SayfaSayısı
		{
			get
			{
				return this._SayfaSayısı;
			}
			set
			{
				if ((this._SayfaSayısı != value))
				{
					this.OnSayfaSayısıChanging(value);
					this.SendPropertyChanging();
					this._SayfaSayısı = value;
					this.SendPropertyChanged("SayfaSayısı");
					this.OnSayfaSayısıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokSayısı", DbType="Int")]
		public System.Nullable<int> StokSayısı
		{
			get
			{
				return this._StokSayısı;
			}
			set
			{
				if ((this._StokSayısı != value))
				{
					this.OnStokSayısıChanging(value);
					this.SendPropertyChanging();
					this._StokSayısı = value;
					this.SendPropertyChanged("StokSayısı");
					this.OnStokSayısıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasımYılı", DbType="Date")]
		public System.Nullable<System.DateTime> BasımYılı
		{
			get
			{
				return this._BasımYılı;
			}
			set
			{
				if ((this._BasımYılı != value))
				{
					this.OnBasımYılıChanging(value);
					this.SendPropertyChanging();
					this._BasımYılı = value;
					this.SendPropertyChanged("BasımYılı");
					this.OnBasımYılıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Durum", DbType="NChar(20)")]
		public string Durum
		{
			get
			{
				return this._Durum;
			}
			set
			{
				if ((this._Durum != value))
				{
					this.OnDurumChanging(value);
					this.SendPropertyChanging();
					this._Durum = value;
					this.SendPropertyChanged("Durum");
					this.OnDurumChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KULLANICI")]
	public partial class KULLANICI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _adı;
		
		private string _şifre;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnadıChanging(string value);
    partial void OnadıChanged();
    partial void OnşifreChanging(string value);
    partial void OnşifreChanged();
    #endregion
		
		public KULLANICI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adı", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string adı
		{
			get
			{
				return this._adı;
			}
			set
			{
				if ((this._adı != value))
				{
					this.OnadıChanging(value);
					this.SendPropertyChanging();
					this._adı = value;
					this.SendPropertyChanged("adı");
					this.OnadıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_şifre", DbType="NChar(10)")]
		public string şifre
		{
			get
			{
				return this._şifre;
			}
			set
			{
				if ((this._şifre != value))
				{
					this.OnşifreChanging(value);
					this.SendPropertyChanging();
					this._şifre = value;
					this.SendPropertyChanged("şifre");
					this.OnşifreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ÜYE")]
	public partial class ÜYE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TCkimlikno;
		
		private System.Nullable<int> _ÜyeNumarası;
		
		private string _ÜyeAdı;
		
		private string _ÜyeSoyadı;
		
		private string _Cinsiyeti;
		
		private System.Nullable<System.DateTime> _DoğumTarihi;
		
		private System.DateTime _ÜyelikTarihi;
		
		private string _TelefonNo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTCkimliknoChanging(string value);
    partial void OnTCkimliknoChanged();
    partial void OnÜyeNumarasıChanging(System.Nullable<int> value);
    partial void OnÜyeNumarasıChanged();
    partial void OnÜyeAdıChanging(string value);
    partial void OnÜyeAdıChanged();
    partial void OnÜyeSoyadıChanging(string value);
    partial void OnÜyeSoyadıChanged();
    partial void OnCinsiyetiChanging(string value);
    partial void OnCinsiyetiChanged();
    partial void OnDoğumTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnDoğumTarihiChanged();
    partial void OnÜyelikTarihiChanging(System.DateTime value);
    partial void OnÜyelikTarihiChanged();
    partial void OnTelefonNoChanging(string value);
    partial void OnTelefonNoChanged();
    #endregion
		
		public ÜYE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCkimlikno", DbType="NChar(11) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TCkimlikno
		{
			get
			{
				return this._TCkimlikno;
			}
			set
			{
				if ((this._TCkimlikno != value))
				{
					this.OnTCkimliknoChanging(value);
					this.SendPropertyChanging();
					this._TCkimlikno = value;
					this.SendPropertyChanged("TCkimlikno");
					this.OnTCkimliknoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ÜyeNumarası", DbType="Int")]
		public System.Nullable<int> ÜyeNumarası
		{
			get
			{
				return this._ÜyeNumarası;
			}
			set
			{
				if ((this._ÜyeNumarası != value))
				{
					this.OnÜyeNumarasıChanging(value);
					this.SendPropertyChanging();
					this._ÜyeNumarası = value;
					this.SendPropertyChanged("ÜyeNumarası");
					this.OnÜyeNumarasıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ÜyeAdı", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string ÜyeAdı
		{
			get
			{
				return this._ÜyeAdı;
			}
			set
			{
				if ((this._ÜyeAdı != value))
				{
					this.OnÜyeAdıChanging(value);
					this.SendPropertyChanging();
					this._ÜyeAdı = value;
					this.SendPropertyChanged("ÜyeAdı");
					this.OnÜyeAdıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ÜyeSoyadı", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string ÜyeSoyadı
		{
			get
			{
				return this._ÜyeSoyadı;
			}
			set
			{
				if ((this._ÜyeSoyadı != value))
				{
					this.OnÜyeSoyadıChanging(value);
					this.SendPropertyChanging();
					this._ÜyeSoyadı = value;
					this.SendPropertyChanged("ÜyeSoyadı");
					this.OnÜyeSoyadıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cinsiyeti", DbType="NChar(10)")]
		public string Cinsiyeti
		{
			get
			{
				return this._Cinsiyeti;
			}
			set
			{
				if ((this._Cinsiyeti != value))
				{
					this.OnCinsiyetiChanging(value);
					this.SendPropertyChanging();
					this._Cinsiyeti = value;
					this.SendPropertyChanged("Cinsiyeti");
					this.OnCinsiyetiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoğumTarihi", DbType="Date")]
		public System.Nullable<System.DateTime> DoğumTarihi
		{
			get
			{
				return this._DoğumTarihi;
			}
			set
			{
				if ((this._DoğumTarihi != value))
				{
					this.OnDoğumTarihiChanging(value);
					this.SendPropertyChanging();
					this._DoğumTarihi = value;
					this.SendPropertyChanged("DoğumTarihi");
					this.OnDoğumTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ÜyelikTarihi", DbType="Date NOT NULL")]
		public System.DateTime ÜyelikTarihi
		{
			get
			{
				return this._ÜyelikTarihi;
			}
			set
			{
				if ((this._ÜyelikTarihi != value))
				{
					this.OnÜyelikTarihiChanging(value);
					this.SendPropertyChanging();
					this._ÜyelikTarihi = value;
					this.SendPropertyChanged("ÜyelikTarihi");
					this.OnÜyelikTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonNo", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string TelefonNo
		{
			get
			{
				return this._TelefonNo;
			}
			set
			{
				if ((this._TelefonNo != value))
				{
					this.OnTelefonNoChanging(value);
					this.SendPropertyChanging();
					this._TelefonNo = value;
					this.SendPropertyChanged("TelefonNo");
					this.OnTelefonNoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
